declare const _default: {
    api: {
        operationFailed: string;
        errorTip: string;
        errorMessage: string;
        timeoutMessage: string;
        apiTimeoutMessage: string;
        apiRequestFailed: string;
        networkException: string;
        networkExceptionMsg: string;
        errMsg400: string;
        errMsg401: string;
        errMsg403: string;
        errMsg404: string;
        errMsg405: string;
        errMsg408: string;
        errMsg500: string;
        errMsg501: string;
        errMsg502: string;
        errMsg503: string;
        errMsg504: string;
        errMsg505: string;
        errMsgUnknown: string;
    };
    app: {
        logoutTip: string;
        logoutMessage: string;
        menuLoading: string;
    };
    errorLog: {
        tableTitle: string;
        tableColumnType: string;
        tableColumnDate: string;
        tableColumnFile: string;
        tableColumnMsg: string;
        tableColumnStackMsg: string;
        tableActionDesc: string;
        modalTitle: string;
        fireVueError: string;
        fireResourceError: string;
        fireAjaxError: string;
        enableMessage: string;
    };
    exception: {
        backLogin: string;
        backHome: string;
        subTitle403: string;
        subTitle404: string;
        subTitle500: string;
        noDataTitle: string;
        networkErrorTitle: string;
        networkErrorSubTitle: string;
    };
    lock: {
        unlock: string;
        alert: string;
        backToLogin: string;
        entry: string;
        placeholder: string;
    };
    login: {
        backSignIn: string;
        signInFormTitle: string;
        mobileSignInFormTitle: string;
        qrSignInFormTitle: string;
        signUpFormTitle: string;
        forgetFormTitle: string;
        signInTitle: string;
        signInDesc: string;
        policy: string;
        scanSign: string;
        loginButton: string;
        registerButton: string;
        rememberMe: string;
        forgetPassword: string;
        otherSignIn: string;
        loginSuccessTitle: string;
        loginSuccessDesc: string;
        accountPlaceholder: string;
        passwordPlaceholder: string;
        smsPlaceholder: string;
        mobilePlaceholder: string;
        policyPlaceholder: string;
        diffPwd: string;
        userName: string;
        password: string;
        confirmPassword: string;
        email: string;
        smsCode: string;
        mobile: string;
    };
};
export default _default;
